/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/fundos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Fundos
         * @description Lista todos os FIIs cadastrados.
         */
        get: operations["listar_fundos_api_v1_fundos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fundos/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detalhe Fundo
         * @description Retorna dados detalhados de um FII pelo ticker.
         */
        get: operations["detalhe_fundo_api_v1_fundos__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ranking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Ranking
         * @description Ranking calculado sob demanda com os pesos canônicos do perfil.
         */
        get: operations["listar_ranking_api_v1_ranking_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ranking/simular": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simular Ranking
         * @description Ranking calculado sob demanda com pesos customizados (soma = 1.0).
         */
        post: operations["simular_ranking_api_v1_ranking_simular_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard Stats
         * @description Estatísticas agregadas para o dashboard.
         */
        get: operations["dashboard_stats_api_v1_dashboard_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/perfil": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Perfil
         * @description Retorna o perfil do investidor.
         */
        get: operations["get_perfil_api_v1_perfil_get"];
        /**
         * Update Perfil
         * @description Atualiza tipo e pesos personalizados do perfil.
         */
        put: operations["update_perfil_api_v1_perfil_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scoring/executar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Executar Scoring
         * @description Executa o scoring multicritério para todos os FIIs com indicadores.
         */
        post: operations["executar_scoring_api_v1_scoring_executar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Clusters
         * @description Lista os clusters com os tickers de cada um.
         */
        get: operations["listar_clusters_api_v1_clusters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clustering/executar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Executar Clustering
         * @description Executa K-Means clustering nos FIIs com dados coletados.
         */
        post: operations["executar_clustering_api_v1_clustering_executar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Verifica se a API está operacional.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ClusterItemOut */
        ClusterItemOut: {
            /** Id */
            id: number;
            /** Nome Interpretado */
            nome_interpretado: string;
            /** Perfil Risco */
            perfil_risco: string;
            /** Descricao */
            descricao: string | null;
            /** Dy Medio */
            dy_medio: number | null;
            /** Volatilidade Media */
            volatilidade_media: number | null;
            /** P Vp Medio */
            p_vp_medio: number | null;
            /** Num Fiis */
            num_fiis: number;
            /** Tickers */
            tickers: string[];
        };
        /** ClusteringResultadoOut */
        ClusteringResultadoOut: {
            /** Clusters Criados */
            clusters_criados: number;
            /** Fundos Clusterizados */
            fundos_clusterizados: number;
        };
        /** DashboardStatsOut */
        DashboardStatsOut: {
            /** Total Fundos */
            total_fundos: number;
            /** Com Dados */
            com_dados: number;
            /** Score Medio */
            score_medio: number | null;
            /** Por Classificacao */
            por_classificacao: {
                [key: string]: number;
            };
            /** Dy Medio */
            dy_medio: number | null;
            /** P Vp Medio */
            p_vp_medio: number | null;
        };
        /** FundoDetalheOut */
        FundoDetalheOut: {
            /** Id */
            id: number;
            /** Ticker */
            ticker: string;
            /** Nome */
            nome: string | null;
            /** Segmento */
            segmento: string | null;
            /** Gestora */
            gestora: string | null;
            indicador: components["schemas"]["IndicadorOut"] | null;
        };
        /** FundoOut */
        FundoOut: {
            /** Id */
            id: number;
            /** Ticker */
            ticker: string;
            /** Nome */
            nome: string | null;
            /** Segmento */
            segmento: string | null;
            /** Gestora */
            gestora: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IndicadorOut */
        IndicadorOut: {
            /** Dy Atual */
            dy_atual: number | null;
            /** Dy 12M */
            dy_12m: number | null;
            /** P Vp */
            p_vp: number | null;
            /** Vacancia Fisica */
            vacancia_fisica: number | null;
            /** Vacancia Financeira */
            vacancia_financeira: number | null;
            /** Liquidez Diaria */
            liquidez_diaria: number | null;
            /** Volatilidade 12M */
            volatilidade_12m: number | null;
            /** Patrimonio Liquido */
            patrimonio_liquido: number | null;
            /** Num Cotistas */
            num_cotistas: number | null;
        };
        /** PerfilOut */
        PerfilOut: {
            /** Id */
            id: string;
            /** Tipo */
            tipo: string;
            /** Pesos Personalizados */
            pesos_personalizados: {
                [key: string]: number;
            } | null;
        };
        /** PerfilUpdate */
        PerfilUpdate: {
            /** Tipo */
            tipo: string;
            /** Pesos Personalizados */
            pesos_personalizados?: {
                [key: string]: number;
            } | null;
        };
        /** PesosIn */
        PesosIn: {
            /** Dy Atual */
            dy_atual: number;
            /** Dy 12M */
            dy_12m: number;
            /** P Vp */
            p_vp: number;
            /** Vacancia Fisica */
            vacancia_fisica: number;
            /** Vacancia Financeira */
            vacancia_financeira: number;
            /** Liquidez Diaria */
            liquidez_diaria: number;
            /** Volatilidade 12M */
            volatilidade_12m: number;
            /** Patrimonio Liquido */
            patrimonio_liquido: number;
            /** Num Cotistas */
            num_cotistas: number;
            /** Segmento */
            segmento: number;
        };
        /** RankingItemOut */
        RankingItemOut: {
            /** Ticker */
            ticker: string;
            /** Nome */
            nome: string | null;
            /** Segmento */
            segmento: string | null;
            /** Score */
            score: number;
            /**
             * Classificacao
             * @enum {string}
             */
            classificacao: "Excelente" | "Bom" | "Regular" | "Evitar";
            /** Dy Atual */
            dy_atual: number | null;
            /** Dy 12M */
            dy_12m: number | null;
            /** P Vp */
            p_vp: number | null;
            /** Vacancia Fisica */
            vacancia_fisica: number | null;
            /** Vacancia Financeira */
            vacancia_financeira: number | null;
            /** Liquidez Diaria */
            liquidez_diaria: number | null;
            /** Volatilidade 12M */
            volatilidade_12m: number | null;
            /** Patrimonio Liquido */
            patrimonio_liquido: number | null;
            /** Num Cotistas */
            num_cotistas: number | null;
        };
        /** ScoringResultadoOut */
        ScoringResultadoOut: {
            /** Calculados */
            calculados: number;
            /** Erros */
            erros: number;
            /** Sem Dados */
            sem_dados: number;
        };
        /** SimularIn */
        SimularIn: {
            pesos: components["schemas"]["PesosIn"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listar_fundos_api_v1_fundos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundoOut"][];
                };
            };
        };
    };
    detalhe_fundo_api_v1_fundos__ticker__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundoDetalheOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_ranking_api_v1_ranking_get: {
        parameters: {
            query?: {
                perfil?: "conservador" | "moderado" | "arrojado";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simular_ranking_api_v1_ranking_simular_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimularIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_stats_api_v1_dashboard_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardStatsOut"];
                };
            };
        };
    };
    get_perfil_api_v1_perfil_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerfilOut"];
                };
            };
        };
    };
    update_perfil_api_v1_perfil_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PerfilUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerfilOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    executar_scoring_api_v1_scoring_executar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoringResultadoOut"];
                };
            };
        };
    };
    listar_clusters_api_v1_clusters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterItemOut"][];
                };
            };
        };
    };
    executar_clustering_api_v1_clustering_executar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusteringResultadoOut"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
