"""adiciona tabela proventos

Revision ID: 247a01afa3cf
Revises: 58410880afe8
Create Date: 2026-06-09 18:46:30.590478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '247a01afa3cf'
down_revision: Union[str, Sequence[str], None] = '58410880afe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fundo_id', sa.Integer(), nullable=False),
    sa.Column('data_com', sa.Date(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('valor_por_cota', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['fundo_id'], ['fundos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fundo_id', 'data_com', 'tipo')
    )
    op.create_index(op.f('ix_proventos_fundo_id'), 'proventos', ['fundo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proventos_fundo_id'), table_name='proventos')
    op.drop_table('proventos')
    # ### end Alembic commands ###
