"""adiciona nome em usuarios

Revision ID: 2e5d637d57ae
Revises: 49135fa7d1b2
Create Date: 2026-06-16 18:51:04.285094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e5d637d57ae'
down_revision: Union[str, Sequence[str], None] = '49135fa7d1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('nome', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'nome')
    # ### end Alembic commands ###
