"""preco_atual em indicadores (RF-29)

Revision ID: 49135fa7d1b2
Revises: e3c302640b86
Create Date: 2026-06-14 14:29:30.619193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49135fa7d1b2'
down_revision: Union[str, Sequence[str], None] = 'e3c302640b86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indicadores', sa.Column('preco_atual', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indicadores', 'preco_atual')
    # ### end Alembic commands ###
