"""cria tabelas iniciais

Revision ID: 77ab8151e029
Revises: 
Create Date: 2026-05-22 20:04:04.974355

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '77ab8151e029'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_interpretado', sa.String(length=100), nullable=False),
    sa.Column('perfil_risco', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('dy_medio', sa.Float(), nullable=True),
    sa.Column('volatilidade_media', sa.Float(), nullable=True),
    sa.Column('p_vp_medio', sa.Float(), nullable=True),
    sa.Column('num_fiis', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fundos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('segmento', sa.String(length=100), nullable=True),
    sa.Column('gestora', sa.String(length=200), nullable=True),
    sa.Column('data_ipo', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fundos_ticker'), 'fundos', ['ticker'], unique=True)
    op.create_table('perfis_investidor',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('pesos_personalizados', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fundo_clusters',
    sa.Column('fundo_id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('data_atribuicao', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.ForeignKeyConstraint(['fundo_id'], ['fundos.id'], ),
    sa.PrimaryKeyConstraint('fundo_id', 'cluster_id')
    )
    op.create_table('indicadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fundo_id', sa.Integer(), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('dy_atual', sa.Float(), nullable=True),
    sa.Column('dy_12m', sa.Float(), nullable=True),
    sa.Column('p_vp', sa.Float(), nullable=True),
    sa.Column('vacancia_fisica', sa.Float(), nullable=True),
    sa.Column('vacancia_financeira', sa.Float(), nullable=True),
    sa.Column('liquidez_diaria', sa.Float(), nullable=True),
    sa.Column('volatilidade_12m', sa.Float(), nullable=True),
    sa.Column('patrimonio_liquido', sa.Float(), nullable=True),
    sa.Column('num_cotistas', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fundo_id'], ['fundos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicadores_fundo_id'), 'indicadores', ['fundo_id'], unique=False)
    op.create_table('scoring_historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fundo_id', sa.Integer(), nullable=False),
    sa.Column('data_execucao', sa.DateTime(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('classificacao', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['fundo_id'], ['fundos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scoring_historico_fundo_id'), 'scoring_historico', ['fundo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scoring_historico_fundo_id'), table_name='scoring_historico')
    op.drop_table('scoring_historico')
    op.drop_index(op.f('ix_indicadores_fundo_id'), table_name='indicadores')
    op.drop_table('indicadores')
    op.drop_table('fundo_clusters')
    op.drop_table('perfis_investidor')
    op.drop_index(op.f('ix_fundos_ticker'), table_name='fundos')
    op.drop_table('fundos')
    op.drop_table('clusters')
    # ### end Alembic commands ###
