"""adiciona classe em fundos

Revision ID: b3a3c4fa69ba
Revises: 77ab8151e029
Create Date: 2026-06-02 20:27:38.737863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3a3c4fa69ba'
down_revision: Union[str, Sequence[str], None] = '77ab8151e029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fundos', sa.Column('classe', sa.String(length=6), server_default='FII', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fundos', 'classe')
    # ### end Alembic commands ###
