"""classe_aplicada em scoring_historico (RF-14)

Revision ID: e3c302640b86
Revises: 247a01afa3cf
Create Date: 2026-06-13 17:04:52.489536

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e3c302640b86"
down_revision: Union[str, Sequence[str], None] = "247a01afa3cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scoring_historico", sa.Column("classe_aplicada", sa.String(length=6), server_default="FII", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scoring_historico", "classe_aplicada")
    # ### end Alembic commands ###
